name: Lint Rust

on:
  workflow_call:
    inputs:
      working-directory:
        default: "."
        required: false
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - working-directory: ${{ inputs.working-directory }}
        run: cargo fmt --all --check && cargo clippy --all-targets --all-features -- -D warnings